//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ckbXaxisResetToZeroIsChecked {
            get {
                return ((bool)(this["ckbXaxisResetToZeroIsChecked"]));
            }
            set {
                this["ckbXaxisResetToZeroIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ckbYaxisResetToZeroIsChecked {
            get {
                return ((bool)(this["ckbYaxisResetToZeroIsChecked"]));
            }
            set {
                this["ckbYaxisResetToZeroIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ckbZaxisResetToZeroIsChecked {
            get {
                return ((bool)(this["ckbZaxisResetToZeroIsChecked"]));
            }
            set {
                this["ckbZaxisResetToZeroIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.00")]
        public decimal Divider4_00 {
            get {
                return ((decimal)(this["Divider4_00"]));
            }
            set {
                this["Divider4_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Milliseconds {
            get {
                return ((int)(this["Milliseconds"]));
            }
            set {
                this["Milliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int mmPerRevolution {
            get {
                return ((int)(this["mmPerRevolution"]));
            }
            set {
                this["mmPerRevolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public string RootAxisX {
            get {
                return ((string)(this["RootAxisX"]));
            }
            set {
                this["RootAxisX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string RootAxisY {
            get {
                return ((string)(this["RootAxisY"]));
            }
            set {
                this["RootAxisY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public string RootAxisZ {
            get {
                return ((string)(this["RootAxisZ"]));
            }
            set {
                this["RootAxisZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XY")]
        public string RootAxisXY {
            get {
                return ((string)(this["RootAxisXY"]));
            }
            set {
                this["RootAxisXY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public decimal Value_0_00 {
            get {
                return ((decimal)(this["Value_0_00"]));
            }
            set {
                this["Value_0_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XaxisChanged {
            get {
                return ((bool)(this["XaxisChanged"]));
            }
            set {
                this["XaxisChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public decimal XaxisStepperCurrent {
            get {
                return ((decimal)(this["XaxisStepperCurrent"]));
            }
            set {
                this["XaxisStepperCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public decimal XaxisStepperMove {
            get {
                return ((decimal)(this["XaxisStepperMove"]));
            }
            set {
                this["XaxisStepperMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400.00")]
        public decimal XaxisMotorSpeed {
            get {
                return ((decimal)(this["XaxisMotorSpeed"]));
            }
            set {
                this["XaxisMotorSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool YaxisChanged {
            get {
                return ((bool)(this["YaxisChanged"]));
            }
            set {
                this["YaxisChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public decimal YaxisStepperCurrent {
            get {
                return ((decimal)(this["YaxisStepperCurrent"]));
            }
            set {
                this["YaxisStepperCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public decimal YaxisStepperMove {
            get {
                return ((decimal)(this["YaxisStepperMove"]));
            }
            set {
                this["YaxisStepperMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400.00")]
        public decimal YaxisMotorSpeed {
            get {
                return ((decimal)(this["YaxisMotorSpeed"]));
            }
            set {
                this["YaxisMotorSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZaxisChanged {
            get {
                return ((bool)(this["ZaxisChanged"]));
            }
            set {
                this["ZaxisChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public decimal ZaxisStepperCurrent {
            get {
                return ((decimal)(this["ZaxisStepperCurrent"]));
            }
            set {
                this["ZaxisStepperCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public decimal ZaxisStepperMove {
            get {
                return ((decimal)(this["ZaxisStepperMove"]));
            }
            set {
                this["ZaxisStepperMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400.00")]
        public decimal ZaxisMotorSpeed {
            get {
                return ((decimal)(this["ZaxisMotorSpeed"]));
            }
            set {
                this["ZaxisMotorSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int zeroXaxis {
            get {
                return ((int)(this["zeroXaxis"]));
            }
            set {
                this["zeroXaxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int zeroYaxis {
            get {
                return ((int)(this["zeroYaxis"]));
            }
            set {
                this["zeroYaxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int zeroZaxis {
            get {
                return ((int)(this["zeroZaxis"]));
            }
            set {
                this["zeroZaxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.00")]
        public decimal MilisecondTimerInterval {
            get {
                return ((decimal)(this["MilisecondTimerInterval"]));
            }
            set {
                this["MilisecondTimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000.00")]
        public decimal MillisecondDelay {
            get {
                return ((decimal)(this["MillisecondDelay"]));
            }
            set {
                this["MillisecondDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public decimal MathPart2Initlz {
            get {
                return ((decimal)(this["MathPart2Initlz"]));
            }
            set {
                this["MathPart2Initlz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.00")]
        public string BuildVersion {
            get {
                return ((string)(this["BuildVersion"]));
            }
            set {
                this["BuildVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stepper Motor Timer:")]
        public string CountDownText {
            get {
                return ((string)(this["CountDownText"]));
            }
            set {
                this["CountDownText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.254.37")]
        public string ZServerIPAddress {
            get {
                return ((string)(this["ZServerIPAddress"]));
            }
            set {
                this["ZServerIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int BaudRate {
            get {
                return ((int)(this["BaudRate"]));
            }
            set {
                this["BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM7")]
        public string XComPort {
            get {
                return ((string)(this["XComPort"]));
            }
            set {
                this["XComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM8")]
        public string YComPort {
            get {
                return ((string)(this["YComPort"]));
            }
            set {
                this["YComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.254.38")]
        public string YServerIPAddress {
            get {
                return ((string)(this["YServerIPAddress"]));
            }
            set {
                this["YServerIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.254.39")]
        public string XServerIPAddress {
            get {
                return ((string)(this["XServerIPAddress"]));
            }
            set {
                this["XServerIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\sfcsarge\\\\source\\\\repos\\\\Stepper\\\\Stepper\\\\Stepper.csproj")]
        public string ProjectFilePath {
            get {
                return ((string)(this["ProjectFilePath"]));
            }
            set {
                this["ProjectFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM10")]
        public string ZComPort {
            get {
                return ((string)(this["ZComPort"]));
            }
            set {
                this["ZComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM10")]
        public string ComPort {
            get {
                return ((string)(this["ComPort"]));
            }
            set {
                this["ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ThreadSleep {
            get {
                return ((int)(this["ThreadSleep"]));
            }
            set {
                this["ThreadSleep"] = value;
            }
        }
    }
}
