//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string BaudRate
        {
            get
            {
                return ((string)(this["BaudRate"]));
            }
            set
            {
                this["BaudRate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ckbXaxisResetToZeroIsChecked
        {
            get
            {
                return ((bool)(this["ckbXaxisResetToZeroIsChecked"]));
            }
            set
            {
                this["ckbXaxisResetToZeroIsChecked"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ckbYaxisResetToZeroIsChecked
        {
            get
            {
                return ((bool)(this["ckbYaxisResetToZeroIsChecked"]));
            }
            set
            {
                this["ckbYaxisResetToZeroIsChecked"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ckbZaxisResetToZeroIsChecked
        {
            get
            {
                return ((bool)(this["ckbZaxisResetToZeroIsChecked"]));
            }
            set
            {
                this["ckbZaxisResetToZeroIsChecked"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string COM1
        {
            get
            {
                return ((string)(this["COM1"]));
            }
            set
            {
                this["COM1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string COM5
        {
            get
            {
                return ((string)(this["COM5"]));
            }
            set
            {
                this["COM5"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string COM4
        {
            get
            {
                return ((string)(this["COM4"]));
            }
            set
            {
                this["COM4"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.00")]
        public decimal Divider4_00
        {
            get
            {
                return ((decimal)(this["Divider4_00"]));
            }
            set
            {
                this["Divider4_00"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int mmPerRevolution
        {
            get
            {
                return ((int)(this["mmPerRevolution"]));
            }
            set
            {
                this["mmPerRevolution"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string Value_0_00
        {
            get
            {
                return ((string)(this["Value_0_00"]));
            }
            set
            {
                this["Value_0_00"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Milliseconds {
            get {
                return ((int)(this["Milliseconds"]));
            }
            set {
                this["Milliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public string RootAxisX {
            get {
                return ((string)(this["RootAxisX"]));
            }
            set {
                this["RootAxisX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string RootAxisY {
            get {
                return ((string)(this["RootAxisY"]));
            }
            set {
                this["RootAxisY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XY")]
        public string RootAxisXY
        {
            get
            {
                return ((string)(this["RootAxisXY"]));
            }
            set
            {
                this["RootAxisXY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public string RootAxisZ {
            get {
                return ((string)(this["RootAxisZ"]));
            }
            set {
                this["RootAxisZ"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string XaxisStepperCurrent
        {
            get
            {
                return ((string)(this["XaxisStepperCurrent"]));
            }
            set
            {
                this["XaxisStepperCurrent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string YaxisStepperCurrent
        {
            get
            {
                return ((string)(this["YaxisStepperCurrent"]));
            }
            set
            {
                this["YaxisStepperCurrent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string ZaxisStepperCurrent
        {
            get
            {
                return ((string)(this["ZaxisStepperCurrent"]));
            }
            set
            {
                this["ZaxisStepperCurrent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000.00")]
        public string XaxisMotorSpeed
        {
            get
            {
                return ((string)(this["XaxisMotorSpeed"]));
            }
            set
            {
                this["XaxisMotorSpeed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000.00")]
        public string ZaxisMotorSpeed
        {
            get
            {
                return ((string)(this["ZaxisMotorSpeed"]));
            }
            set
            {
                this["ZaxisMotorSpeed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string XaxisStepperMove
        {
            get
            {
                return ((string)(this["XaxisStepperMove"]));
            }
            set
            {
                this["XaxisStepperMove"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string YaxisStepperMove
        {
            get
            {
                return ((string)(this["YaxisStepperMove"]));
            }
            set
            {
                this["YaxisStepperMove"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string ZaxisStepperMove
        {
            get
            {
                return ((string)(this["ZaxisStepperMove"]));
            }
            set
            {
                this["ZaxisStepperMove"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000.00")]
        public string YaxisMotorSpeed
        {
            get
            {
                return ((string)(this["YaxisMotorSpeed"]));
            }
            set
            {
                this["YaxisMotorSpeed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int zeroXaxis
        {
            get
            {
                return ((int)(this["zeroXaxis"]));
            }
            set
            {
                this["zeroXaxis"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int zeroYaxis
        {
            get
            {
                return ((int)(this["zeroYaxis"]));
            }
            set
            {
                this["zeroYaxis"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int zeroZaxis
        {
            get
            {
                return ((int)(this["zeroZaxis"]));
            }
            set
            {
                this["zeroZaxis"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XaxisChanged {
            get {
                return ((bool)(this["XaxisChanged"]));
            }
            set {
                this["XaxisChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool YaxisChanged {
            get {
                return ((bool)(this["YaxisChanged"]));
            }
            set {
                this["YaxisChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZaxisChanged {
            get {
                return ((bool)(this["ZaxisChanged"]));
            }
            set {
                this["ZaxisChanged"] = value;
            }
        }
    }
}
