//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string XaxisStepperCurrent {
            get {
                return ((string)(this["XaxisStepperCurrent"]));
            }
            set {
                this["XaxisStepperCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string YaxisStepperCurrent {
            get {
                return ((string)(this["YaxisStepperCurrent"]));
            }
            set {
                this["YaxisStepperCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string ZaxisStepperCurrent {
            get {
                return ((string)(this["ZaxisStepperCurrent"]));
            }
            set {
                this["ZaxisStepperCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000.00")]
        public string XaxisMotorSpeed {
            get {
                return ((string)(this["XaxisMotorSpeed"]));
            }
            set {
                this["XaxisMotorSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000.00")]
        public string ZaxisMotorSpeed {
            get {
                return ((string)(this["ZaxisMotorSpeed"]));
            }
            set {
                this["ZaxisMotorSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string XaxisStepperMove {
            get {
                return ((string)(this["XaxisStepperMove"]));
            }
            set {
                this["XaxisStepperMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string YaxisStepperMove {
            get {
                return ((string)(this["YaxisStepperMove"]));
            }
            set {
                this["YaxisStepperMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string ZaxisStepperMove {
            get {
                return ((string)(this["ZaxisStepperMove"]));
            }
            set {
                this["ZaxisStepperMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string BaudRate {
            get {
                return ((string)(this["BaudRate"]));
            }
            set {
                this["BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string DefaultValues {
            get {
                return ((string)(this["DefaultValues"]));
            }
            set {
                this["DefaultValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000.00")]
        public string YaxisMotorSpeed {
            get {
                return ((string)(this["YaxisMotorSpeed"]));
            }
            set {
                this["YaxisMotorSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ckbXaxisResetToZeroIsChecked {
            get {
                return ((bool)(this["ckbXaxisResetToZeroIsChecked"]));
            }
            set {
                this["ckbXaxisResetToZeroIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ckbYaxisResetToZeroIsChecked {
            get {
                return ((bool)(this["ckbYaxisResetToZeroIsChecked"]));
            }
            set {
                this["ckbYaxisResetToZeroIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ckbZaxisResetToZeroIsChecked {
            get {
                return ((bool)(this["ckbZaxisResetToZeroIsChecked"]));
            }
            set {
                this["ckbZaxisResetToZeroIsChecked"] = value;
            }
        }
    }
}
